### ISSUE TITLE
请问 action 是如何处理 300ms 延迟 && 点透问题的呢？

### ISSUE THREAD

**Issue by tcdona** [cssmagic/action#25]

**Comment by cssmagic** [comment]
Action 的关注点与 300ms 相关问题不在一个层面，因此没有对此特意处理。如果开发者很在意 300ms 延迟及其延伸出的问题，可以考虑使用 [FastClick](https://github.com/ftlabs/fastclick) 这个库来处理。

我回头会测试一下 Action 和 FastClick 的兼容性。谢谢提醒。

**Comment by tcdona** [comment]
了解啦，多谢回复

**Comment by cssmagic** [comment]
随 Chrome 之后，Safari 也将去除 300ms 延时，因此不再测试 Action 和 FastClick 的兼容性。
